version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/TORrents/
hooks:
  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: ubuntu
